site_name: Security Tips
site_url: https://security-tips.vincd.com/
site_description: A collection of security tips
site_author: Vincent D. (@vincd)

theme:
  name: readthedocs
  custom_dir: 'theme/'

markdown_extensions:
  - markdown_new_tab
  - markdown_prism
  - meta

google_analytics: ['UA-128044070-4', 'security-tips.vincd.com']

nav:
  - Home: index.md
  - Ports: ports.md
  - Cloud: cloud.md
  - Windows:
    - General: windows.md
    - Event ID: eventid.md
    - Powershell: powershell.md
  - Android: android.md
  - Linux: linux.md
  - Web:
    - HTTP: http.md
    - XSS: xss.md
    - API: API.md
    - OAuth: oauth.md
    - 'Path Traversal': path-traversal.md
    - 'File Upload': file-upload.md
    - JWT: jwt.md
    - IIS: iis.md
    - Nginx: nginx.md
    - GraphQL: graphql.md
    - Spring Boot: spring_boot.md
  - SQL:
    - PostgreSQL: postgresql.md
    - MariaDB: mariadb.md
    - Oracle: oracle.md
  - CVE:
    - CVE-2016-3714: cve/CVE-2016-3714.md
    - CVE-2017-5638: cve/CVE-2017-5638.md
    - CVE-2017-8291: cve/CVE-2017-8291.md
    - CVE-2019-1388: cve/CVE-2019-1388/index.md
    - CVE-2019-11510: cve/CVE-2019-11510.md
    - CVE-2019-11581: cve/CVE-2019-11581.md
    - CVE-2019-16759: cve/CVE-2019-16759.md
    - CVE-2019-19781: cve/CVE-2019-19781.md
    - CVE-2020-0618: cve/CVE-2020-0618.md
    - CVE-2020-0688: cve/CVE-2020-0688.md
    - CVE-2020-1938: cve/CVE-2020-1938.md
    - CVE-2020-5902: cve/CVE-2020-5902.md
    - FFmpeg HLS vulnerability: cve/ffmpeg.md
  - SDR:
    - 'Challs Dont Matter Anymore': sdr/challs-dont-matter-anymore/hackingforsoju.md
    - 'lit-fam': sdr/lit-fam/hackingforsoju.md
  - Languages:
    - PHP: php.md
    - Java: java.md
    - Python: python.md
    - Node: node.md
  - Misc:
    - Firefox: firefox.md
    - Docker: docker.md
    - Kubernetes: kubernetes.md
    - Citrix: citrix.md
    - SSH: ssh.md
    - FTP: ftp.md
    - Git: git.md
    - Kafka: kafka.md
    - ISCSI: iscsi.md
    - Reverse Shell: reverse-shell.md
    - Zip: zip.md
    - XXE: xxe.md
    - Others: miscs.md

dev_addr: 0.0.0.0:4000
