site_name: Security Tips
site_url: https://security-tips.vincd.com/
site_description: A collection of security tips
site_author: Vincent D. (@vincd)

theme:
  name: readthedocs
  custom_dir: 'theme/'
  highlightjs: true
  hljs_languages:
    - line-numbers
    - clike
    - yaml
    - powershell
    - bash
    - nginx
    - python
    - markup
    - markup-templating
    - php

markdown_extensions:
  - markdown_new_tab
  - markdown_prism

google_analytics: ['UA-128044070-4', 'security-tips.vincd.com']

nav:
  - Home: index.md
  - Ports: ports.md
  - Android: android.md
  - Cloud: cloud.md
  - Containers:
    - Docker: docker.md
    - Kubernetes: kubernetes.md
  - Windows: windows.md
  - Powershell: powershell.md
  - Linux: linux.md
  - SSH: ssh.md
  - FTP: ftp.md
  - XXE: xxe.md
  - Zip: zip.md
  - Kafka: kafka.md
  - Web:
    - XSS: xss.md
    - API: API.md
    - OAuth: oauth.md
    - 'Path Traversal': path-traversal.md
    - GraphQL: graphql.md
    - PHP: php.md
    - JWT: jwt.md
    - IIS: iis.md
    - Nginx: nginx.md
  - SQL:
    - PostgreSQL: postgresql.md
  - CVE:
    - CVE-2016-3714: cve/CVE-2016-3714.md
    - CVE-2019-1388: cve/CVE-2019-1388/index.md
    - CVE-2019-11510: cve/CVE-2019-11510.md
    - CVE-2019-11581: cve/CVE-2019-11581.md
    - CVE-2019-16759: cve/CVE-2019-16759.md
    - CVE-2019-19781: cve/CVE-2019-19781.md
    - CVE-2020-0618: cve/CVE-2020-0618.md
    - CVE-2020-0688: cve/CVE-2020-0688.md
    - CVE-2020-1938: cve/CVE-2020-1938.md
    - CVE-2020-5902: cve/CVE-2020-5902.md
    - FFmpeg HLS vulnerability: cve/ffmpeg.md
  - SDR:
    - 'Challs Dont Matter Anymore': sdr/challs-dont-matter-anymore/hackingforsoju.md
    - 'lit-fam': sdr/lit-fam/hackingforsoju.md
  - Misc:
    - Firefox: firefox.md
    - Git: git.md
    - ISCSI: iscsi.md
    - Java: java.md
    - Python: python.md
    - Node: node.md
    - Reverse Shell: reverse-shell.md
    - Spring Boot: spring_boot.md
    - WAF: waf.md
    - Others: miscs.md

dev_addr: 0.0.0.0:4000
