site_name: Security Tips
site_url: https://security-tips.vincd.com/
site_description: A collection of security tips
site_author: Vincent D. (@vincd)

theme:
  name: readthedocs
  custom_dir: 'theme/'
  highlightjs: true
  hljs_languages:
    - yaml
    - powershell
    - bash
    - nginx
    - python

markdown_extensions:
  - markdown_new_tab

google_analytics: ['UA-128044070-2', 'security-tips.vincd.com']

nav:
  - Home: index.md
  - AWS: aws.md
  - Containers:
    - Docker: docker.md
    - Kubernetes: kubernetes.md
  - Windows: windows.md
  - Linux: linux.md
  - XXE: xxe.md
  - Zip: zip.md
  - Kafka: kafka.md
  - Web:
    - XSS: xss.md
    - API: API.md
    - OAuth: oauth.md
    - 'Path Traversal': path-traversal.md
    - GraphQL: graphql.md
    - Git: git.md
    - JWT: jwt.md
    - IIS: iis.md
    - Nginx: nginx.md
  - CVE:
    - CVE-2019-1388: cve/CVE-2019-1388/index.md
    - CVE-2019-11510: cve/CVE-2019-11510.md
    - CVE-2019-11581: cve/CVE-2019-11581.md
    - CVE-2019-16759: cve/CVE-2019-16759.md
  - SDR:
    - 'Challs Dont Matter Anymore': sdr/challs-dont-matter-anymore/hackingforsoju.md
    - 'lit-fam': sdr/lit-fam/hackingforsoju.md
  - Misc:
    - Firefox: firefox.md
    - ISCSI: iscsi.md
    - Reverse Shell: reverse-shell.md
    - WAF: waf.md
