site_name: Security Tips
site_url: https://security-tips.vincd.com/
site_description: A collection of security tips
site_author: Vincent D. (@vincd)

theme:
  name: readthedocs
  custom_dir: 'theme/'
  highlightjs: true

google_analytics: ['UA-128044070-2', 'security-tips.vincd.com']

nav:
  - Home: index.md
  - AWS: aws.md
  - Containers:
    - Docker: docker.md
    - Kubernetes: kubernetes.md
  - Nginx: nginx.md
  - Windows: windows.md
  - Linux: linux.md
  - XXE: xxe.md
  - Zip: zip.md
  - Web:
    - XSS: xss.md
    - API: API.md
    - OAuth: oauth.md
    - 'Path Traversal': path-traversal.md
    - GraphQL: graphql.md
    - Git: git.md
    - JWT: jwt.md
  - Configuration Review: configuration-review.md
  - CVE:
    - CVE-2019-1388: cve/CVE-2019-1388/
    - CVE-2019-11581: cve/CVE-2019-11581.md
  - SDR:
    - 'Challs Dont Matter Anymore': sdr/challs-dont-matter-anymore/hackingforsoju.md
    - 'lit-fam': sdr/lit-fam/hackingforsoju.md
  - Misc:
    - Firefox: firefox.md
    - ISCSI: iscsi.md
    - Reverse Shell: reverse-shell.md
    - WAF: waf.md
